# Generated by Django 2.2.6 on 2020-03-13 16:25

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension



class Migration(migrations.Migration):

    dependencies = [
        ('onlineform', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
