# Generated by Django 2.2.6 on 2020-03-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineform', '0004_auto_20200314_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='client_value',
            field=models.FloatField(help_text='Enter in USD'),
        ),
    ]
