# Generated by Django 2.2.6 on 2020-03-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineform', '0005_auto_20200314_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
